server:
  port: 8082
spring:
  application:
    name: payment-domain
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME_PAYMENT:fs_payment_prod}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
axon:
  axonserver:
    servers: ${AXON_SERVER:localhost:8124}
  eventhandling:
    poolsize: 10
  serializer:
    general: xstream
  repository:
    snapshot-filter: 10
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}




