server:
  port: 8081
spring:
  application:
    name: identity-domain
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME_IDENTITY:fs_identity_prod}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
jwt:
  secret: ${JWT_SECRET:super_secret_jwt_key_for_flashsale_project_that_is_very_long}
  expiration: ${JWT_EXPIRATION_MS:86400000}
grpc:
  server:
    port: 9091   # gRPC server port — service-to-service calls (Order, Payment, Cart...)
