spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_PRODUCT:product_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.flashsale: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

dev-data:
  enabled: true
  reset: ${DEV_DATA_RESET:false}
