server:
  port: 8090
spring:
  application:
    name: product-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true             # Virtual Threads Java 21+ — bật cho MVC, không cần cho WebFlux
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${spring.application.name}-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.flashsale.*
  mongodb:
    uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:root}:${MONGO_INITDB_ROOT_PASSWORD_ENCODED:root}@${MONGO_HOST:localhost}:27017/${DB_NAME_PRODUCT:fs_product_prod}?authSource=admin
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 60000ms
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 40
    should-enforce-registration-at-init: false
    fetch-registry: true
    register-with-eureka: true
    enabled: true
