spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:flashsale_platform}?currentSchema=product
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123!}

logging:
  level:
    com.flashsale: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

dev-data:
  enabled: true
  reset: ${DEV_DATA_RESET:false}
