server:
  port: 8084
spring:
  application:
    name: promotion-domain
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME_PROMOTION:fs_promo_prod}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:123456}
axon:
  axonserver:
    servers: ${AXON_SERVER:localhost:8124}
  eventhandling:
    poolsize: 10
  serializer:
    general: xstream
  repository:
    snapshot-filter: 10
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}




