server:
  port: 8088   # ← đã đổi từ 8089 (conflict với Cart Service)
spring:
  application:
    name: worker-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME_WORKER:fs_worker_prod}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
